[package]
name = "jctl2gray"
version = "0.1.0"
authors = ["Anton Dort-Golts"]

[dependencies]
notify = "4.0.0"
libflate = "0.1"
rand = "0.4"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
toml = "0.4"
clap = "2.0"
log = "0.4"
loggerv = "0.7"
lazy_static = "1.0"
regex = "0.2"
